package com.myspace.claimsconnect_rulesbase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class sla implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("slaType")
	private java.lang.String slaType;
	@org.kie.api.definition.type.Label("duration")
	private String duration;
	@org.kie.api.definition.type.Label("escalationType")
	private java.lang.String escalationType;
	@org.kie.api.definition.type.Label("policyAmount")
	private java.lang.Double policyAmount;

	@org.kie.api.definition.type.Label("escalateTo")
	private java.lang.String escalateTo;

	@org.kie.api.definition.type.Label(value = "personaRole")
	private java.lang.String personaRole;

	@org.kie.api.definition.type.Label(value = "personaRoleId")
	private java.lang.String personaRoleId;

	public sla() {
	}

	public java.lang.String getSlaType() {
		return this.slaType;
	}

	public void setSlaType(java.lang.String slaType) {
		this.slaType = slaType;
	}

	public java.lang.String getEscalationType() {
		return this.escalationType;
	}

	public void setEscalationType(java.lang.String escalationType) {
		this.escalationType = escalationType;
	}

	public java.lang.Double getPolicyAmount() {
		return this.policyAmount;
	}

	public void setPolicyAmount(java.lang.Double policyAmount) {
		this.policyAmount = policyAmount;
	}

	public java.lang.String getEscalateTo() {
		return this.escalateTo;
	}

	public void setEscalateTo(java.lang.String escalateTo) {
		this.escalateTo = escalateTo;
	}

	public java.lang.String getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.String duration) {
		this.duration = duration;
	}

	public java.lang.String getPersonaRole() {
		return this.personaRole;
	}

	public void setPersonaRole(java.lang.String personaRole) {
		this.personaRole = personaRole;
	}

	public java.lang.String getPersonaRoleId() {
		return this.personaRoleId;
	}

	public void setPersonaRoleId(java.lang.String personaRoleId) {
		this.personaRoleId = personaRoleId;
	}

	public sla(java.lang.String slaType, java.lang.String duration,
			java.lang.String escalationType, java.lang.Double policyAmount,
			java.lang.String escalateTo, java.lang.String personaRole,
			java.lang.String personaRoleId) {
		this.slaType = slaType;
		this.duration = duration;
		this.escalationType = escalationType;
		this.policyAmount = policyAmount;
		this.escalateTo = escalateTo;
		this.personaRole = personaRole;
		this.personaRoleId = personaRoleId;
	}

}